export enum HazardType {
  FLOOD = 'FLOOD',
  LANDSLIDE = 'LANDSLIDE',
  TSUNAMI = 'TSUNAMI',
  CYCLONE = 'CYCLONE',
  EARTHQUAKE = 'EARTHQUAKE',
  DROUGHT = 'DROUGHT',
  ROAD_BLOCKAGE = 'ROAD_BLOCKAGE',
  RISING_RIVER = 'RISING_RIVER',
  FALLEN_TREE = 'FALLEN_TREE',
  BUILDING_DAMAGE = 'BUILDING_DAMAGE',
  FIRE = 'FIRE',
  OTHER = 'OTHER',
}
