export enum WarningStatus {
  DRAFT = 'DRAFT',
  ISSUED = 'ISSUED',
  BROADCASTING = 'BROADCASTING',
  BROADCAST_COMPLETE = 'BROADCAST_COMPLETE',
  ESCALATED = 'ESCALATED',
  CANCELLED = 'CANCELLED',
}
