export enum UserRole {
  DMC_OFFICER = 'DMC_OFFICER',
  ADMIN = 'ADMIN',
  CITIZEN = 'CITIZEN',
  VOLUNTEER = 'VOLUNTEER',
  DUTY_OFFICER = 'DUTY_OFFICER',
  RESCUE_TEAM = 'RESCUE_TEAM',
  DISTRICT_OFFICER = 'DISTRICT_OFFICER',
}
