/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/**/*.{html,ts}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#dce1ff",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#001551",
        "on-tertiary-fixed-variant": "#93000b",
        "tertiary-fixed": "#ffdad6",
        "on-tertiary": "#ffffff",
        "surface": "#f8f9ff",
        "secondary": "#1d4ed8",
        "secondary-container": "#4069f2",
        "surface-variant": "#d3e4fe",
        "on-error-container": "#93000a",
        "surface-container-high": "#dce9ff",
        "on-primary-container": "#77849c",
        "secondary-fixed-dim": "#b7c4ff",
        "surface-bright": "#f8f9ff",
        "background": "#f8f9ff",
        "surface-container-low": "#eff4ff",
        "surface-container-lowest": "#ffffff",
        "outline": "#75777d",
        "on-secondary": "#ffffff",
        "surface-dim": "#cbdbf5",
        "surface-container-highest": "#d3e4fe",
        "inverse-on-surface": "#eaf1ff",
        "on-tertiary-container": "#f63a35",
        "error": "#ba1a1a",
        "primary-fixed-dim": "#bac7e1",
        "on-surface-variant": "#44474c",
        "on-background": "#0b1c30",
        "on-error": "#ffffff",
        "tertiary-container": "#410002",
        "inverse-surface": "#213145",
        "on-primary-fixed": "#0e1c2f",
        "primary": "#000000",
        "inverse-primary": "#bac7e1",
        "on-surface": "#0b1c30",
        "tertiary-fixed-dim": "#ffb4ab",
        "primary-fixed": "#d6e3fe",
        "on-primary-fixed-variant": "#3a475c",
        "surface-container": "#e5eeff",
        "primary-container": "#0e1c2f",
        "on-tertiary-fixed": "#410002",
        "surface-tint": "#525f75",
        "on-secondary-fixed-variant": "#0039b5",
        "on-secondary-container": "#fffbff",
        "error-container": "#ffdad6",
        "tertiary": "#000000",
        "outline-variant": "#c5c6cd"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        "gutter": "1rem",
        "space-2xl": "2rem",
        "space-xs": "0.25rem",
        "space-md": "0.75rem",
        "margin-mobile": "0.75rem",
        "space-xl": "1.5rem",
        "space-lg": "1rem",
        "gutter-compact": "0.5rem",
        "space-sm": "0.5rem",
        "margin": "1.5rem"
      },
      fontFamily: {
        "display-lg": ["Inter"],
        "headline-md": ["Inter"],
        "headline-sm": ["Inter"],
        "body-md": ["Inter"],
        "headline-lg": ["Inter"],
        "data-mono": ["Inter"],
        "label-md": ["Inter"],
        "headline-xl": ["Inter"],
        "label-sm": ["Inter"],
        "body-sm": ["Inter"],
        "body-lg": ["Inter"]
      },
      fontSize: {
        "display-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.025em", fontWeight: "700" }],
        "headline-md": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["15px", { lineHeight: "20px", letterSpacing: "-0.005em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0", fontWeight: "400" }],
        "headline-lg": ["22px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "data-mono": ["13px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "600" }],
        "headline-xl": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "0", fontWeight: "400" }]
      }
    }
  },
  plugins: [],
}
